apiVersion: aws.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: eks-cluster-argocd
  namespace: team-b
spec:
  id: eks-cluster-argocd
  parameters:
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: eks-cluster-argocd
