apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rds-mariadb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: crossplane-demo
  source:
    path: examples/RDS
    repoURL: https://github.com/stevendborrelli/argocd-uxp
    targetRevision: HEAD
